TASK_INVENTORY = [
    # --- STAGE 1: THREAT ATTRIBUTION ---
    {
        "id": "T1",
        "name": "Malware Identification",
        "target": "Malware delivery or toolset",
        "tools": ["ner_tool", "sum_tool"],
        "depends_on": [],
        "produces": ["malware_or_tool_candidates"],
        "consumes": ["raw_artifact"],
    },
    {
        "id": "T2",
        "name": "Signature Matching",
        "target": "Techniques from known threat groups",
        "tools": ["ner_tool", "sim_tool"],
        "depends_on": ["T1"],
        "produces": ["signature_candidates"],
        "consumes": ["malware_or_tool_candidates", "raw_artifact"],
    },
    {
        "id": "T3",
        "name": "Temporal Pattern Matching",
        "target": "Known work schedules",
        "tools": ["rex_tool"],
        "depends_on": [],
        "produces": ["temporal_indicators"],
        "consumes": ["raw_artifact"],
    },
    {
        "id": "T4",
        "name": "Affiliation Linking",
        "target": "Source organizations",
        "tools": ["ner_tool", "map_tool"],
        "depends_on": ["T1", "T7"],
        "produces": ["affiliation_links"],
        "consumes": ["malware_or_tool_candidates", "ioc_inventory"],
    },
    {
        "id": "T5",
        "name": "Geographic Analysis",
        "target": "Geographic or cultural indicators",
        "tools": ["ner_tool", "sim_tool"],
        "depends_on": ["T1", "T7"],
        "produces": ["geo_cultural_indicators"],
        "consumes": ["malware_or_tool_candidates", "ioc_inventory"],
    },
    {
        "id": "T6",
        "name": "Victimology Profiling",
        "target": "Targeted victims or attacker motives",
        "tools": ["ner_tool", "rex_tool"],
        "depends_on": ["T1", "T7"],
        "produces": ["victimology_profile"],
        "consumes": ["malware_or_tool_candidates", "ioc_inventory"],
    },
    {
        "id": "T7",
        "name": "Infrastructure Extraction",
        "target": "Domains, IPs, URLs, or file hashes",
        "tools": ["ner_tool", "rex_tool", "sum_tool"],
        "depends_on": [],
        "produces": ["ioc_inventory", "infrastructure_entities"],
        "consumes": ["raw_artifact"],
    },
    {
        "id": "T8",
        "name": "Actor Identification",
        "target": "The threat group or actor (e.g., APT28)",
        "tools": ["ner_tool", "rag_tool", "map_tool"],
        "depends_on": ["T1", "T2", "T4", "T7"],
        "produces": ["actor_candidates"],
        "consumes": ["malware_or_tool_candidates", "signature_candidates", "affiliation_links", "ioc_inventory"],
    },
    {
        "id": "T9",
        "name": "Campaign Correlation",
        "target": "Threat campaigns or incidents",
        "tools": ["ner_tool", "map_tool"],
        "depends_on": ["T1", "T2", "T7", "T8"],
        "produces": ["campaign_candidates"],
        "consumes": ["malware_or_tool_candidates", "signature_candidates", "ioc_inventory", "actor_candidates"],
    },
    # --- STAGE 2: BEHAVIOR ANALYSIS ---
    {
        "id": "T10",
        "name": "File System Activity Detection",
        "target": "Suspicious file creation, deletion, or access",
        "tools": ["spa_tool", "ner_tool", "sum_tool"],
        "depends_on": ["T7"],
        "produces": ["file_activity_findings"],
        "consumes": ["ioc_inventory", "raw_artifact"],
    },
    {
        "id": "T11",
        "name": "Network Behavior Profiling",
        "target": "Patterns of external communication (e.g., C2)",
        "tools": ["spa_tool", "ner_tool", "sum_tool"],
        "depends_on": ["T7"],
        "produces": ["network_behavior_findings"],
        "consumes": ["ioc_inventory", "raw_artifact"],
    },
    {
        "id": "T12",
        "name": "Credential Access Detection",
        "target": "Theft or misuse of credentials",
        "tools": ["spa_tool", "ner_tool", "sum_tool"],
        "depends_on": ["T7", "T13", "T14"],
        "produces": ["credential_access_findings"],
        "consumes": ["ioc_inventory", "execution_context", "command_script_findings"],
    },
    {
        "id": "T13",
        "name": "Execution Context Analysis",
        "target": "Execution behaviors by user or process",
        "tools": ["spa_tool", "ner_tool", "sum_tool"],
        "depends_on": ["T7"],
        "produces": ["execution_context"],
        "consumes": ["ioc_inventory", "raw_artifact"],
    },
    {
        "id": "T14",
        "name": "Command & Script Analysis",
        "target": "Suspicious commands or scripts",
        "tools": ["spa_tool", "ner_tool", "sum_tool"],
        "depends_on": ["T7", "T13"],
        "produces": ["command_script_findings"],
        "consumes": ["ioc_inventory", "execution_context"],
    },
    {
        "id": "T15",
        "name": "Privilege Escalation Inference",
        "target": "Privilege escalation attempts",
        "tools": ["spa_tool", "ner_tool", "sum_tool"],
        "depends_on": ["T12", "T13", "T14"],
        "produces": ["privilege_findings"],
        "consumes": ["credential_access_findings", "execution_context", "command_script_findings"],
    },
    {
        "id": "T16",
        "name": "Evasion Behavior Detection",
        "target": "Evasion or obfuscation techniques",
        "tools": ["spa_tool", "ner_tool", "sum_tool"],
        "depends_on": ["T10", "T13", "T14"],
        "produces": ["evasion_findings"],
        "consumes": ["file_activity_findings", "execution_context", "command_script_findings"],
    },
    {
        "id": "T17",
        "name": "Event Sequence Reconstruction",
        "target": "Timeline of attack-related events",
        "tools": ["sum_tool"],
        "depends_on": ["T10", "T11", "T12", "T13", "T14", "T16"],
        "produces": ["attack_timeline"],
        "consumes": [
            "file_activity_findings",
            "network_behavior_findings",
            "credential_access_findings",
            "execution_context",
            "command_script_findings",
            "evasion_findings",
        ],
    },
    {
        "id": "T18",
        "name": "TTP Extraction",
        "target": "Tactics, techniques, and procedures",
        "tools": ["rag_tool", "map_tool"],
        "depends_on": ["T2", "T7", "T10", "T11", "T12", "T13", "T14", "T16", "T17"],
        "produces": ["mitre_attack_candidates", "ttp_mapping"],
        "consumes": ["signature_candidates", "ioc_inventory", "attack_timeline", "behavior_findings"],
    },
    # --- STAGE 3: PRIORITIZATION ---
    {
        "id": "T19",
        "name": "Attack Vector Classification",
        "target": "Exploitation vectors (e.g., network, local, physical)",
        "tools": ["sum_tool", "cls_tool"],
        "depends_on": ["T10", "T11", "T13", "T17", "T18"],
        "produces": ["attack_vector_classification"],
        "consumes": ["behavior_findings", "attack_timeline", "ttp_mapping"],
    },
    {
        "id": "T20",
        "name": "Attack Complexity Classification",
        "target": "Level of hurdles required to carry out the attack",
        "tools": ["sum_tool", "cls_tool"],
        "depends_on": ["T10", "T13", "T17", "T18"],
        "produces": ["attack_complexity_classification"],
        "consumes": ["file_activity_findings", "execution_context", "attack_timeline", "ttp_mapping"],
    },
    {
        "id": "T21",
        "name": "Privileges Requirement Detection",
        "target": "Level of access privileges an attacker needs",
        "tools": ["sum_tool", "cls_tool"],
        "depends_on": ["T12", "T13", "T15"],
        "produces": ["privileges_required_classification"],
        "consumes": ["credential_access_findings", "execution_context", "privilege_findings"],
    },
    {
        "id": "T22",
        "name": "User Interaction Categorization",
        "target": "If exploitation requires user participation",
        "tools": ["sum_tool", "cls_tool"],
        "depends_on": ["T10", "T13", "T14"],
        "produces": ["user_interaction_classification"],
        "consumes": ["file_activity_findings", "execution_context", "command_script_findings"],
    },
    {
        "id": "T23",
        "name": "Attack Scope Detection",
        "target": "If the vulnerability affects one/multiple components",
        "tools": ["sum_tool", "cls_tool"],
        "depends_on": ["T10", "T11", "T13", "T17"],
        "produces": ["attack_scope_classification"],
        "consumes": ["file_activity_findings", "network_behavior_findings", "execution_context", "attack_timeline"],
    },
    {
        "id": "T24",
        "name": "Impact Level Classification",
        "target": "Consequences on confidentiality, integrity, and availability",
        "tools": ["sum_tool", "cls_tool"],
        "depends_on": ["T10", "T11", "T12", "T14", "T16", "T17"],
        "produces": ["impact_level_classification"],
        "consumes": ["behavior_findings", "attack_timeline"],
    },
    {
        "id": "T25",
        "name": "Severity Scoring",
        "target": "A numerical score indicating the overall attack severity",
        "tools": ["sum_tool", "math_tool"],
        "depends_on": ["T19", "T20", "T21", "T22", "T23", "T24"],
        "produces": ["severity_score"],
        "consumes": [
            "attack_vector_classification",
            "attack_complexity_classification",
            "privileges_required_classification",
            "user_interaction_classification",
            "attack_scope_classification",
            "impact_level_classification",
        ],
    },
    # --- STAGE 4: RESPONSE & MITIGATION ---
    {
        "id": "T26",
        "name": "Playbook Recommendation",
        "target": "Relevant response actions based on threat type",
        "tools": ["rag_tool", "sum_tool"],
        "depends_on": ["T1", "T7", "T17", "T18", "T25"],
        "produces": ["playbook_recommendations"],
        "consumes": ["malware_or_tool_candidates", "ioc_inventory", "attack_timeline", "ttp_mapping", "severity_score"],
    },
    {
        "id": "T27",
        "name": "Security Control Adjustment",
        "target": "Firewall rules, EDR settings, or group policies",
        "tools": ["rag_tool", "sum_tool"],
        "depends_on": ["T7", "T16", "T18", "T25"],
        "produces": ["security_control_recommendations"],
        "consumes": ["ioc_inventory", "evasion_findings", "ttp_mapping", "severity_score"],
    },
    {
        "id": "T28",
        "name": "Patch Code Generation",
        "target": "Code snippets to patch the vulnerability",
        "tools": ["rag_tool", "sum_tool"],
        "depends_on": ["T19", "T20", "T25"],
        "produces": ["patch_guidance"],
        "consumes": ["attack_vector_classification", "attack_complexity_classification", "severity_score"],
    },
    {
        "id": "T29",
        "name": "Patch Tool Suggestion",
        "target": "Security tools or utilities",
        "tools": ["rag_tool", "sum_tool"],
        "depends_on": ["T18", "T25"],
        "produces": ["patch_tool_suggestions"],
        "consumes": ["ttp_mapping", "severity_score"],
    },
    {
        "id": "T30",
        "name": "Advisory Correlation",
        "target": "Security advisories or best practices",
        "tools": ["rag_tool", "sum_tool"],
        "depends_on": ["T1", "T8", "T18", "T25"],
        "produces": ["advisory_correlations"],
        "consumes": ["malware_or_tool_candidates", "actor_candidates", "ttp_mapping", "severity_score"],
    },
]


TASK_BY_ID = {task["id"]: task for task in TASK_INVENTORY}


def clone_task(task_id):
    task = TASK_BY_ID[task_id]
    return {
        **task,
        "tools": list(task.get("tools", [])),
        "depends_on": list(task.get("depends_on", [])),
        "produces": list(task.get("produces", [])),
        "consumes": list(task.get("consumes", [])),
    }
